name: Daily Contracts Finder Pipeline

on:
  schedule:
    - cron: '0 7 * * *'  # runs every day at 7am UTC
  workflow_dispatch:     # allows manual trigger from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python scripts/cf_daily_pipeline.py
